import { useState } from "react";
import { useAuth } from "../auth/AuthContext";
export default function Auth() {
  const { authenticate } = useAuth(); const [mode, setMode] = useState("login"); const [form, setForm] = useState({ name: "", phone: "", password: "", businessName: "", craftType: "", experienceYears: "", certificates: "", credentials: "" }); const [error, setError] = useState("");
  const submit = async (e) => { e.preventDefault(); try { setError(""); await authenticate(mode, form); } catch (err) { setError(err.message); } };
  const change = (key) => (e) => setForm({ ...form, [key]: e.target.value });
  const skip = async () => { try { await authenticate("register", { name: form.name || "Artisan", phone: form.phone, password: form.password, certificates: [], credentials: [] }); } catch (err) { setError(err.message); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><div className="brand-icon">K</div><h1>KarigarConnect</h1><p>{mode === "login" ? "Sign in to your artisan workspace" : "Create your artisan workspace"}</p>{mode === "register" && <><input placeholder="Your name" value={form.name} onChange={change("name")} required /><input placeholder="Business / workshop name" value={form.businessName} onChange={change("businessName")} /><input placeholder="Primary craft" value={form.craftType} onChange={change("craftType")} /><input placeholder="Years of experience" type="number" min="0" value={form.experienceYears} onChange={change("experienceYears")} /><input placeholder="Certificates (comma separated)" value={form.certificates} onChange={change("certificates")} /><input placeholder="Credentials / awards (comma separated)" value={form.credentials} onChange={change("credentials")} /></>}<input placeholder="Phone number" inputMode="tel" value={form.phone} onChange={change("phone")} required /><input placeholder="Password (minimum 6 characters)" type="password" value={form.password} onChange={change("password")} required />{error && <p className="auth-error">{error}</p>}<button type="submit">{mode === "login" ? "Sign in" : "Create profile"}</button>{mode === "register" && <button type="button" className="auth-switch" onClick={skip}>Skip details — complete later</button>}<button type="button" className="auth-switch" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "New artisan? Create an account" : "Already have an account? Sign in"}</button></form></main>;
}
